# used for development
# docker-compose.override.yml is automatically used by docker-compose when no
# option -f is provided

version: '2'

services:
  odoo:
    tty: true
    stdin_open: true
    ports:
      - 8069
      - 8072
    volumes:
      - "data-odoo-pytest-cache:/odoo/.cache"
      - "./odoo/src:/odoo/src"
      - "./odoo/local-src:/odoo/local-src"
      - "./odoo/external-src:/odoo/external-src"
      - "./odoo/songs:/odoo/songs"
      - "./odoo/migration.yml:/odoo/migration.yml"
      - "./odoo/data:/odoo/data"
    environment:
      - MARABUNTA_MODE=demo  # could be 'full' for the db with all the data
      - MARABUNTA_ALLOW_SERIE=True  # should not be set in production

  db:
    ports:
      - 5432

  nginx:
    ports:
      - 80:80

volumes:
  data-odoo-pytest-cache:
